### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by noribeth-m** [NCAR/ACOM-Python-Tutorial#7]
Hello there. 

When I attempting to run the ./scripts/install_extentions.sh, it says that the install_extentions.sh file doesn't exist. Since I am a very beginner with coding and python in general, im not sure if this is a critical step to installing/running miniconda. The only files that appear within the scripts directory are:
download_cartopy_assets.py
post_build.sh

Hoping I could get some feedback on next steps or how to resolve this issue. Thanks.

**Comment by kmpaul** [comment]
@nmarisca1:  Try it now.  @andersy005 just updated the environment file.

**Comment by andersy005** [comment]
@nmarisca1, 

> When I attempting to run the ./scripts/install_extentions.sh, it says that the install_extentions.sh file doesn't exist.

With the [updated instructions](https://github.com/NCAR/ACOM-Python-Tutorial#create-environments), the extension installation step isn't needed. If you had already installed conda and created the conda environments, make sure to run the following commands to update your existing environments. 

```bash
conda env update -f environments/base.yaml
conda env update -f environments/tutorial.yaml
```

**Comment by noribeth-m** [comment]
@kmpaul @andersy005: Thank you both so much! I tried it out and the environment files updated successfully.
